### ISSUE TITLE
Weaher does not work

### ISSUE THREAD

**Issue by EricEon** [poucotm/Guna#12]
Following the readme to show weather using the settings for the openweathermap.org api, i keep getting this error....
`GUNA : ERROR ________________________________________________
Traceback (most recent call last):
  File "./python3.3/urllib/request.py", line 1248, in do_open
  File "./python3.3/http/client.py", line 1065, in request
  File "./python3.3/http/client.py", line 1103, in _send_request
  File "./python3.3/http/client.py", line 1061, in endheaders
  File "./python3.3/http/client.py", line 906, in _send_output
  File "./python3.3/http/client.py", line 844, in send
  File "./python3.3/http/client.py", line 822, in connect
  File "./python3.3/socket.py", line 417, in create_connection
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pouco\AppData\Roaming\Sublime Text 3\Packages\Guna\core\engine.py", line 877, in update_weather
  File "./python3.3/urllib/request.py", line 156, in urlopen
  File "./python3.3/urllib/request.py", line 469, in open
  File "./python3.3/urllib/request.py", line 487, in _open
  File "./python3.3/urllib/request.py", line 447, in _call_chain
  File "./python3.3/urllib/request.py", line 1274, in http_open
  File "./python3.3/urllib/request.py", line 1251, in do_open
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>`

**Comment by EricEon** [comment]
Got it to work, thanks for a great theme. :+1:
