### ISSUE TITLE
GUNA : Error is occured on set sidebar widget: weather

### ISSUE THREAD

**Issue by F4Jonatas** [poucotm/Guna#22]
GUNA : Error is occured. Please, see the trace-back message in Sublime Console.
```
GUNA : ERROR ________________________________________________
Traceback (most recent call last):
  File "C:\Users\pouco\AppData\Roaming\Sublime Text 3\Packages\Guna\core\engine.py", line 747, in jDsqIU_oxSmbzL
  File "./python3.3/urllib/request.py", line 156, in urlopen
  File "./python3.3/urllib/request.py", line 475, in open
  File "./python3.3/urllib/request.py", line 587, in http_response
  File "./python3.3/urllib/request.py", line 513, in error
  File "./python3.3/urllib/request.py", line 447, in _call_chain
  File "./python3.3/urllib/request.py", line 595, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
============================================================
```

**Comment by poucotm** [comment]
You have correct settings like this ? 
	"weather": {
		"appid": "751842343244355e36",
		"city_name": "seongnam,KR",
		"proxy": ""
	},

**Comment by F4Jonatas** [comment]
I'm not using or have a proxy.

**Comment by poucotm** [comment]
You don't need to fill proxy if you don't use, but appid, city_name should be filled.

**Comment by F4Jonatas** [comment]
I'm using the same configuration as the previous version

"sidebar_widget": [ "weather" ],
"weather": {
	"appid": "e9e31a15a6bfaa***",
	"city_name": "3456160"
}

**Comment by poucotm** [comment]
city_name is weird.  once test with your browser.
http://api.openweathermap.org/data/2.5/weather?q=3456160&APPID=e9e31a15a6bfaa***

`{"cod":"404","message":"city not found"}`

**Comment by F4Jonatas** [comment]
Agora está fucionando perfeitamente.
`"city_name": "Nova Iguacu"`
